version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.0"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker"
    labels:
      traefik.enable: "true"
      traefik.backend: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./backends.toml:/backends.toml
    networks:
            - traefik
networks:
        traefik:
                external: true

